version: "3.9"
services:
  client:
    build:
      context: client
      dockerfile: client/Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

  api:
    build:
      context: api
      dockerfile: api/Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8080:3000"
    networks:
      - app-network

  nginx:
    image: nginx:1.19.10-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

#  db:
#    image: mysql:5.7.22
#    container_name: db
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: your_mysql_root_password
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
